In [25]:
import numpy as np

In [26]:
def sigmoid(x):
    return 1/(1+np.exp(x))

In [27]:
def sigmoid_prime(x):
    return sigmoid(x)*(1-sigmoid(x))

In [28]:
learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

In [29]:
# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])
w

array([ 0.5, -0.5,  0.3,  0.1])

In [30]:
# The node's linear combination of inputs and weights
h = np.dot(x, w)
h

0.7999999999999999

In [31]:
# Output of neural network
nn_output = sigmoid(h)
nn_output

0.31002551887238755

In [32]:
# Error of neural network
error = y - nn_output
error

0.18997448112761245

In [33]:
# The error term
error_term = error * sigmoid_prime(x)


# The sigmoid_prime function calculates sigmoid(h) twice,
# but we've already calculated it once. We can make this
# code more efficient by calculating the derivative directly
# rather than calling sigmoid_prime, like this:
error_term = error * nn_output * (1 - nn_output)
error_term

0.04063738360460798

In [34]:
# Change in weights (Mind this step)
del_w = learnrate * error_term * x
del_w

array([0.02031869, 0.04063738, 0.06095608, 0.08127477])

In [35]:
print('Neural Network output:')
print(nn_output)

Neural Network output:
0.31002551887238755


In [36]:
print('Amount of Error:')
print(error)

Amount of Error:
0.18997448112761245


In [37]:
print('Change in Weights:')
print(del_w)

Change in Weights:
[0.02031869 0.04063738 0.06095608 0.08127477]
