In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [3]:
# Network size
N_input = 4
N_hidden = 3
N_output = 2

In [12]:
np.random.seed(42)
# Make some fake data
X = np.random.randn(4)
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [19]:
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_input_to_hidden

array([[ 0.03613956,  0.15380366, -0.0035826 ],
       [ 0.15646437, -0.26197451,  0.08219025],
       [ 0.00870471, -0.02990074,  0.00917608],
       [-0.19875689, -0.02196719,  0.03571126]])

In [20]:
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
weights_hidden_to_output

array([[ 0.1477894 , -0.05182702],
       [-0.08084936, -0.0501757 ],
       [ 0.09154021,  0.03287511]])

In [21]:
# Forward Pass through network
hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

Hidden-layer Output:
[0.4253724  0.51494433 0.51179507]


In [22]:
output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Output-layer Output:
[0.51701404 0.49223608]
